name: "endurance_2012"
segment {
    type: STRAIGHT
    length: 23.11303023
}
segment {
    type: CORNER
    radius: 11.44526289
    angle: 2.902305562
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 4.194056388
}
segment {
    type: CORNER
    radius: 9.802387605
    angle: 1.014559037
    direction: LEFT
}
segment {
    type: CORNER
    radius: 10.36322073
    angle: 1.794196956
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 13.9019558
}
segment {
    type: CORNER
    radius: 17.67843536
    angle: 2.694786089
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 29.33096266
}
segment {
    type: CORNER
    radius: 12.6492253
    angle: 0.6965603161
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 11.9024638
}
segment {
    type: CORNER
    radius: 8.382016764
    angle: 1.570445934
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 4.319024638
}
segment {
    type: CORNER
    radius: 8.382016764
    angle: 0.8936078222
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 68.39116078
}
segment {
    type: CORNER
    radius: 9.144018288
    angle: 2.168744297
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 10.97282195
    angle: 0.7449058956
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 46.51866904
}
segment {
    type: CORNER
    radius: 13.71602743
    angle: 2.052854532
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 8.241808484
}
segment {
    type: CORNER
    radius: 19.81203962
    angle: 1.766795309
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 10.71069342
}
segment {
    type: CORNER
    radius: 26.97485395
    angle: 2.388655597
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 15.42291085
}
segment {
    type: CORNER
    radius: 18.28803658
    angle: 0.950330975
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 12.22555245
}
segment {
    type: CORNER
    radius: 13.86842774
    angle: 2.264388259
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 12.54559309
}
segment {
    type: CORNER
    radius: 9.144018288
    angle: 0.7887136228
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 18.28803658
    angle: 0.8393281283
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 16.76403353
    angle: 0.8873246422
    direction: LEFT
}
segment {
    type: CORNER
    radius: 9.144018288
    angle: 1.088211869
    direction: LEFT
}
segment {
    type: CORNER
    radius: 10.66802134
    angle: 1.235517534
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 10.04318009
}
segment {
    type: CORNER
    radius: 7.953771908
    angle: 0.5427969389
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 64.002032
}
segment {
    type: CORNER
    radius: 8.991617983
    angle: 0.9344484922
    direction: LEFT
}
segment {
    type: CORNER
    radius: 14.17322835
    angle: 2.063850097
    direction: LEFT
}
segment {
    type: CORNER
    radius: 19.0500381
    angle: 0.9548688272
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 55.68402337
}
segment {
    type: CORNER
    radius: 19.54229108
    angle: 0.5096357111
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 15.24003048
    angle: 1.124863753
    direction: LEFT
}
segment {
    type: CORNER
    radius: 15.58140716
    angle: 1.018922357
    direction: LEFT
}
segment {
    type: CORNER
    radius: 17.57632715
    angle: 0.8772017411
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 16.002032
    angle: 0.4996873428
    direction: RIGHT
}
segment {
    type: STRAIGHT
    length: 39.51435103
}
segment {
    type: CORNER
    radius: 30.48006096
    angle: 1.356119683
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 17.57175514
}
segment {
    type: CORNER
    radius: 21.58902718
    angle: 0.61889323
    direction: LEFT
}
segment {
    type: CORNER
    radius: 12.82600965
    angle: 0.6218602872
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 15.95631191
    angle: 0.8941314206
    direction: RIGHT
}
segment {
    type: CORNER
    radius: 8.851409703
    angle: 0.9171697472
    direction: LEFT
}
segment {
    type: CORNER
    radius: 12.62484125
    angle: 1.526289142
    direction: LEFT
}
segment {
    type: STRAIGHT
    length: 48.2499365
}