massProperties {
    vehicleMass: 225
    driverMass: 75
    cornerInertia: 0.303
    yawInertia: 100
    rearMassFraction: 0.501
    cgHeight: 0.31
}

suspensionConfig {
    wheelBase: 1.582
    trackWidth: 1.214
    rearRollStiffnessFraction: 0.5
}

powertrainConfig {
    accumulatorConfig {
        cellType: VTC6
        nSeries: 72
        nParallel: 10
        stateOfCharge: 1.0
    }

    motorType: AMK
    frontRatio: 0
    rearRatio: 4
    inverterEff: 0.97

    tireConfig {
        tireType: R25B_18x7_5
        # Knockdowns correlated from skidpad and accel data
        longKnockdown: 0.6
        latKnockdown: 0.47
    }
}

aeroConfig {
    AC_d: 1.41
    AC_l: 2.4
    dragHeight: 0.58
    rearAeroFraction: 0.452
}