# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/policy_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/policy_config.proto\"k\n\x0cPolicyConfig\x12\n\n\x02\x64t\x18\x01 \x01(\x01\x12\x19\n\x11maxDischargePower\x18\x02 \x01(\x01\x12\x15\n\rmaxRegenPower\x18\x03 \x01(\x01\x12\x1d\n\tdrsPolicy\x18\x04 \x01(\x0e\x32\n.DrsPolicy*N\n\tDrsPolicy\x12\n\n\x06\x43LOSED\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\r\n\tDYNAMIC_1\x10\x02\x12\r\n\tDYNAMIC_2\x10\x03\x12\r\n\tDYNAMIC_3\x10\x04\x62\x06proto3')

_DRSPOLICY = DESCRIPTOR.enum_types_by_name['DrsPolicy']
DrsPolicy = enum_type_wrapper.EnumTypeWrapper(_DRSPOLICY)
CLOSED = 0
OPEN = 1
DYNAMIC_1 = 2
DYNAMIC_2 = 3
DYNAMIC_3 = 4


_POLICYCONFIG = DESCRIPTOR.message_types_by_name['PolicyConfig']
PolicyConfig = _reflection.GeneratedProtocolMessageType('PolicyConfig', (_message.Message,), {
  'DESCRIPTOR' : _POLICYCONFIG,
  '__module__' : 'proto.policy_config_pb2'
  # @@protoc_insertion_point(class_scope:PolicyConfig)
  })
_sym_db.RegisterMessage(PolicyConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRSPOLICY._serialized_start=138
  _DRSPOLICY._serialized_end=216
  _POLICYCONFIG._serialized_start=29
  _POLICYCONFIG._serialized_end=136
# @@protoc_insertion_point(module_scope)
