# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import track_pb2 as proto_dot_track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/state.proto\x1a\x11proto/track.proto\"\xbe\x03\n\x0cVehicleState\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08velocity\x18\x02 \x01(\x01\x12\r\n\x05\x61\x63\x63\x65l\x18\x03 \x01(\x01\x12\x10\n\x08position\x18\x04 \x01(\x01\x12\x0f\n\x07\x63urrent\x18\x0b \x01(\x01\x12\x0f\n\x07voltage\x18\x0c \x01(\x01\x12\r\n\x05power\x18\r \x01(\x01\x12\x15\n\rstateOfCharge\x18\x0e \x01(\x01\x12\x16\n\x0emotorHeatTotal\x18\x15 \x01(\x01\x12\x14\n\x0cinverterHeat\x18\x16 \x01(\x01\x12\x18\n\x10\x66rontMotorTorque\x18\x17 \x01(\x01\x12\x17\n\x0frearMotorTorque\x18\x18 \x01(\x01\x12\x17\n\x0f\x66rontMotorSpeed\x18\x19 \x01(\x01\x12\x16\n\x0erearMotorSpeed\x18\x1a \x01(\x01\x12\x11\n\tdragForce\x18\x1f \x01(\x01\x12\x11\n\tdownForce\x18  \x01(\x01\x12!\n\x0b\x63ontrolMode\x18( \x01(\x0e\x32\x0c.ControlMode\x12\x0b\n\x03\x64rs\x18) \x01(\x08\x12\x15\n\rsegmentNumber\x18\x32 \x01(\x01\x12!\n\x0bsegmentType\x18\x33 \x01(\x0e\x32\x0c.SegmentType\"6\n\x0fVehicleStateLog\x12#\n\x0cvehicleState\x18\x01 \x03(\x0b\x32\r.VehicleState*S\n\x0b\x43ontrolMode\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0c\x41\x43\x43\x45LERATING\x10\x01\x12\x0c\n\x08\x43OASTING\x10\x02\x12\x0b\n\x07\x42RAKING\x10\x03\x12\r\n\tCORNERING\x10\x04\x62\x06proto3')

_CONTROLMODE = DESCRIPTOR.enum_types_by_name['ControlMode']
ControlMode = enum_type_wrapper.EnumTypeWrapper(_CONTROLMODE)
NONE = 0
ACCELERATING = 1
COASTING = 2
BRAKING = 3
CORNERING = 4


_VEHICLESTATE = DESCRIPTOR.message_types_by_name['VehicleState']
_VEHICLESTATELOG = DESCRIPTOR.message_types_by_name['VehicleStateLog']
VehicleState = _reflection.GeneratedProtocolMessageType('VehicleState', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLESTATE,
  '__module__' : 'proto.state_pb2'
  # @@protoc_insertion_point(class_scope:VehicleState)
  })
_sym_db.RegisterMessage(VehicleState)

VehicleStateLog = _reflection.GeneratedProtocolMessageType('VehicleStateLog', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLESTATELOG,
  '__module__' : 'proto.state_pb2'
  # @@protoc_insertion_point(class_scope:VehicleStateLog)
  })
_sym_db.RegisterMessage(VehicleStateLog)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLMODE._serialized_start=545
  _CONTROLMODE._serialized_end=628
  _VEHICLESTATE._serialized_start=41
  _VEHICLESTATE._serialized_end=487
  _VEHICLESTATELOG._serialized_start=489
  _VEHICLESTATELOG._serialized_end=543
# @@protoc_insertion_point(module_scope)
