# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/track.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/track.proto\"\x8e\x01\n\x07Segment\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.SegmentType\x12\x0e\n\x06length\x18\n \x01(\x01\x12\x13\n\x0bstartOffset\x18\x0b \x01(\x01\x12\x0e\n\x06radius\x18\x14 \x01(\x01\x12\r\n\x05\x61ngle\x18\x15 \x01(\x01\x12#\n\tdirection\x18\x16 \x01(\x0e\x32\x10.CornerDirection\"0\n\x05Track\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x07segment\x18\x02 \x03(\x0b\x32\x08.Segment*\'\n\x0bSegmentType\x12\x0c\n\x08STRAIGHT\x10\x00\x12\n\n\x06\x43ORNER\x10\x01*&\n\x0f\x43ornerDirection\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.track_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEGMENTTYPE._serialized_start=216
  _SEGMENTTYPE._serialized_end=255
  _CORNERDIRECTION._serialized_start=257
  _CORNERDIRECTION._serialized_end=295
  _SEGMENT._serialized_start=22
  _SEGMENT._serialized_end=164
  _TRACK._serialized_start=166
  _TRACK._serialized_end=214
# @@protoc_insertion_point(module_scope)
